name: Build Kivy App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel \
            libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev
          pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Preinstall Android SDK tools (includes AIDL)
        run: |
          mkdir -p ~/.android/sdk/cmdline-tools/latest
          cd ~/.android/sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.android/sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/.android/sdk
          export ANDROIDNDK=$ANDROIDSDK/ndk-bundle
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: family-app
          path: bin/*.apk
